### ISSUE TITLE
Datatype has no field names, used to work....

### ISSUE THREAD

**Issue by blairn** [JuliaOpt/GLPKMathProgInterface.jl#27]
I'm getting 

ERROR: type DataType has no field names
 in model at C:\Users\Blair\.julia\v0.5\GLPKMathProgInterface\src\GLPKInterfaceMIP.jl:187
 in _buildInternalModel_nlp at C:\Users\Blair\.julia\v0.5\JuMP\src\nlp.jl:538
 in buildInternalModel at C:\Users\Blair\.julia\v0.5\JuMP\src\solvers.jl:186
 in solve at C:\Users\Blair\.julia\v0.5\JuMP\src\solvers.jl:77
 in eval at boot.jl:264

This looks like a regression, since it used to work, and line which fails is from the last checkin.

if this IS expected behavour, how do I specify field names so I can run the solver?

**Comment by blairn** [comment]
opps - that was the fix which was checked in :/

Mmmm I'll have to read up on how to get the latest version loaded, since Pkg.update() Pkg.add("GLPKMathProgInterface") doesn't seem to work.

Sorry for the invalid bug report.

**Comment by mlubin** [comment]
I went ahead and tagged the fix: https://github.com/JuliaLang/METADATA.jl/pull/4007
