### ISSUE TITLE
Lazy callback error

### ISSUE THREAD

**Issue by emreyamangil** [JuliaOpt/GLPKMathProgInterface.jl#30]
When I want to use lazy callback using GLPK I get the following error message:

`````````````````````````````````````````````````````````````````````````````````
ERROR: LoadError: MethodError: `cbgetmipsolution` has no method matching cbgetmipsolution(::GLPKMathProgInterface.GLPKInterfaceMIP.GLPKCallbackData)
Closest candidates are:
  cbgetmipsolution(::GLPKMathProgInterface.GLPKInterfaceMIP.GLPKCallbackData, !Matched::Array{T,1})
``````````````````````````````````````````````````````````````````````````````````

I need the signature match with other mip solvers like CPLEX and GuRoBi (I can hack this to my code in the worst case though if its a big overhaul), many thanks!!

**Comment by mlubin** [comment]
@emreyamangil, I fixed this issue but GLPK still doesn't work as a branch and cut solver. It looks like there are some numerical issues, not sure if on the Pajarito side or GLPK side.
