### ISSUE TITLE
Replace MathProgBase with MathOptInterface

### ISSUE THREAD

**Issue by OliverEvans96** [JuliaOpt/GLPKMathProgInterface.jl#56]
[MathProgBase](https://github.com/JuliaOpt/MathProgBase.jl) has been deprecated in favor of [MathOptInterface](https://github.com/JuliaOpt/MathOptInterface.jl).

**Comment by odow** [comment]
See https://github.com/JuliaOpt/GLPKMathProgInterface.jl/pull/57

You can now use `GLPK.Optimizer` from https://github.com/JuliaOpt/GLPK.jl
```julia
using GLPK, JuMP
model = Model(with_optimizer(GLPK.Optimizer, presolve = true))
```

**Comment by OliverEvans96** [comment]
Ah, okay! Do you know how I can specify the optimizer? E.g. MIP.

Thanks!
Oliver

**Comment by OliverEvans96** [comment]
Sorry if the above question is answered elsewhere already - I wasn't sure
where to find documentation for GLPK.Optimizer

**Comment by odow** [comment]
You don't have to choose between the MIP/LP optimizer anymore. Please open an issue on GLPK.jl to add documentation for GLPK.Optimizer.

**Comment by OliverEvans96** [comment]
Ah, thank you! https://github.com/JuliaOpt/GLPK.jl/issues/93
