### ISSUE TITLE
how to solve--"Cgl0013I Postprocessed model is infeasible - possible tolerance issue - try without preprocessing"

### ISSUE THREAD

**Issue by zhengdongxia** [JuliaOpt/GLPKMathProgInterface.jl#62]
Hi,I encountered the following problems.

Although the optimization result is optimal, the log shows that it is not feasible and  prompts the statement that "Cgl0013I Postprocessed model is infeasible - possible tolerance issue - try without preprocessing" .But I can't find where to modify the preprocessing in Python.Also,I don't know if it will work.

Thank you in advance for all your help!

The below text  is the log 

`Problem MODEL has 918 rows, 944 columns and 3251 elements
Coin0008I MODEL read with 0 errors
Continuous objective value is 14 - 0.03 seconds
Cgl0003I 0 fixed, 0 tightened bounds, 27 strengthened rows, 1844 substitutions
Cgl0003I 0 fixed, 0 tightened bounds, 233 strengthened rows, 0 substitutions
Cgl0003I 0 fixed, 0 tightened bounds, 289 strengthened rows, 0 substitutions
Cgl0003I 0 fixed, 0 tightened bounds, 240 strengthened rows, 0 substitutions
Cgl0003I 0 fixed, 0 tightened bounds, 121 strengthened rows, 0 substitutions
Cgl0003I 0 fixed, 0 tightened bounds, 62 strengthened rows, 0 substitutions
Cgl0003I 0 fixed, 0 tightened bounds, 57 strengthened rows, 0 substitutions
Cgl0003I 0 fixed, 0 tightened bounds, 42 strengthened rows, 0 substitutions
Cgl0003I 0 fixed, 0 tightened bounds, 30 strengthened rows, 0 substitutions
Cgl0004I processed model has 322 rows, 511 columns (403 integer (403 of which binary)) and 2152 elements
Cbc0038I Initial state - 81 integers unsatisfied sum - 16.0741
Cbc0038I Pass   1: suminf.    4.69748 (32) obj. -8.46975 iterations 164
Cbc0038I Pass   2: suminf.    4.69748 (32) obj. -8.46975 iterations 1
Cbc0038I Pass   3: suminf.    0.30614 (2) obj. -1 iterations 55
Cbc0038I Solution found of -1
Cbc0038I Relaxing continuous gives -1
Cbc0038I Before mini branch and bound, 320 integers at bound fixed and 55 continuous
Cbc0038I Full problem 322 rows 511 columns, reduced to 86 rows 78 columns
Cbc0038I Mini branch and bound improved solution from -1 to -4 (0.39 seconds)
Cbc0038I Round again with cutoff of -5.70576
Cbc0038I Pass   4: suminf.    4.69748 (32) obj. -8.46975 iterations 0
Cbc0038I Pass   5: suminf.    4.69748 (32) obj. -8.46975 iterations 4
Cbc0038I Pass   6: suminf.    2.32885 (31) obj. -5.70576 iterations 103
Cbc0038I Pass   7: suminf.    2.30135 (26) obj. -5.70576 iterations 7
Cbc0038I Pass   8: suminf.    5.83405 (36) obj. -5.70576 iterations 145
Cbc0038I Pass   9: suminf.    5.25151 (36) obj. -5.70576 iterations 27
Cbc0038I Pass  10: suminf.    4.81249 (26) obj. -5.70576 iterations 82
Cbc0038I Pass  11: suminf.    3.91828 (20) obj. -5.70576 iterations 60
Cbc0038I Pass  12: suminf.    1.71988 (17) obj. -5.70576 iterations 95
Cbc0038I Pass  13: suminf.    1.58358 (14) obj. -5.70576 iterations 30
Cbc0038I Pass  14: suminf.    2.28868 (17) obj. -5.70576 iterations 66
Cbc0038I Pass  15: suminf.    1.73395 (16) obj. -5.70576 iterations 38
Cbc0038I Pass  16: suminf.    1.58344 (13) obj. -5.70576 iterations 89
Cbc0038I Pass  17: suminf.    1.02871 (12) obj. -5.70576 iterations 48
Cbc0038I Pass  18: suminf.    1.78558 (13) obj. -5.70576 iterations 68
Cbc0038I Pass  19: suminf.    1.23085 (12) obj. -5.70576 iterations 44
Cbc0038I Pass  20: suminf.    1.79048 (12) obj. -5.70576 iterations 56
Cbc0038I Pass  21: suminf.    1.23575 (11) obj. -5.70576 iterations 33
Cbc0038I Pass  22: suminf.    1.94086 (13) obj. -5.70576 iterations 58
Cbc0038I Pass  23: suminf.    1.38613 (12) obj. -5.70576 iterations 23
Cbc0038I Pass  24: suminf.    1.58344 (13) obj. -5.70576 iterations 69
Cbc0038I Pass  25: suminf.    1.02871 (12) obj. -5.70576 iterations 37
Cbc0038I Pass  26: suminf.    1.94086 (13) obj. -5.70576 iterations 53
Cbc0038I Pass  27: suminf.    5.24680 (35) obj. -5.70576 iterations 143
Cbc0038I Pass  28: suminf.    4.27519 (25) obj. -5.70576 iterations 69
Cbc0038I Pass  29: suminf.    3.84257 (24) obj. -5.70576 iterations 82
Cbc0038I Pass  30: suminf.    3.51184 (23) obj. -5.70576 iterations 62
Cbc0038I Pass  31: suminf.    4.66810 (21) obj. -5.70576 iterations 77
Cbc0038I Pass  32: suminf.    2.35358 (17) obj. -5.70576 iterations 46
Cbc0038I Pass  33: suminf.    1.92501 (15) obj. -5.70576 iterations 9
Cbc0038I No solution found this major pass
Cbc0038I Before mini branch and bound, 264 integers at bound fixed and 35 continuous
Cbc0038I Full problem 322 rows 511 columns, reduced to 168 rows 175 columns
Cbc0038I Mini branch and bound improved solution from -4 to -5 (0.75 seconds)
Cbc0038I Round again with cutoff of -7.21162
Cbc0038I Pass  33: suminf.    4.69748 (32) obj. -8.46975 iterations 0
Cbc0038I Pass  34: suminf.    4.69748 (32) obj. -8.46975 iterations 4
Cbc0038I Pass  35: suminf.    4.22876 (46) obj. -7.21162 iterations 156
Cbc0038I Pass  36: suminf.    3.53845 (44) obj. -7.21162 iterations 30
Cbc0038I Pass  37: suminf.    3.13625 (42) obj. -7.21162 iterations 43
Cbc0038I Pass  38: suminf.    4.26146 (45) obj. -7.21162 iterations 46
Cbc0038I Pass  39: suminf.    3.12915 (48) obj. -7.21162 iterations 45
Cbc0038I Pass  40: suminf.    3.13254 (45) obj. -7.21162 iterations 66
Cbc0038I Pass  41: suminf.    2.87087 (48) obj. -7.21162 iterations 21
Cbc0038I Pass  42: suminf.    8.87323 (40) obj. -7.21162 iterations 154
Cbc0038I Pass  43: suminf.    3.03103 (45) obj. -7.21162 iterations 84
Cbc0038I Pass  44: suminf.    2.99021 (47) obj. -7.21162 iterations 14
Cbc0038I Pass  45: suminf.   10.09064 (34) obj. -7.21162 iterations 116
Cbc0038I Pass  46: suminf.    3.67310 (37) obj. -7.21162 iterations 84
Cbc0038I Pass  47: suminf.    3.13015 (47) obj. -7.21162 iterations 55
Cbc0038I Pass  48: suminf.    6.50761 (42) obj. -7.21162 iterations 119
Cbc0038I Pass  49: suminf.    2.99021 (47) obj. -7.21162 iterations 67
Cbc0038I Pass  50: suminf.    2.99021 (47) obj. -7.21162 iterations 5
Cbc0038I Pass  51: suminf.    3.17363 (34) obj. -7.21162 iterations 91
Cbc0038I Pass  52: suminf.    2.78485 (34) obj. -7.21162 iterations 39
Cbc0038I Pass  53: suminf.    3.14095 (29) obj. -7.21162 iterations 107
Cbc0038I Pass  54: suminf.    2.51873 (27) obj. -7.21162 iterations 7
Cbc0038I Pass  55: suminf.    6.46257 (53) obj. -7.21162 iterations 106
Cbc0038I Pass  56: suminf.    6.04426 (45) obj. -7.21162 iterations 41
Cbc0038I Pass  57: suminf.    5.09498 (42) obj. -7.21162 iterations 30
Cbc0038I Pass  58: suminf.    4.70309 (41) obj. -7.21162 iterations 4
Cbc0038I Pass  59: suminf.    8.00873 (47) obj. -7.21162 iterations 95
Cbc0038I Pass  60: suminf.    5.72757 (53) obj. -7.21162 iterations 50
Cbc0038I Pass  61: suminf.    4.42860 (26) obj. -7.42325 iterations 72
Cbc0038I Pass  62: suminf.    4.21697 (27) obj. -7.21162 iterations 11
Cbc0038I No solution found this major pass
Cbc0038I Before mini branch and bound, 255 integers at bound fixed and 38 continuous
Cbc0038I Full problem 322 rows 511 columns, reduced to 163 rows 181 columns
Cbc0038I Mini branch and bound did not improve solution (1.08 seconds)
Cbc0038I After 1.08 seconds - Feasibility pump exiting with objective of -5 - took 0.74 seconds
Cbc0012I Integer solution of -5 found by feasibility pump after 0 iterations and 0 nodes (1.08 seconds)
Cbc0038I Full problem 322 rows 511 columns, reduced to 114 rows 124 columns
Cbc0031I 21 added rows had average density of 336.90476
Cbc0013I At root node, 21 cuts changed objective from -12.058519 to -11.95329 in 40 passes
Cbc0014I Cut generator 0 (Probing) - 0 row cuts average 0.0 elements, 0 column cuts (0 active)  in 0.151 seconds - new frequency is -100
Cbc0014I Cut generator 1 (Gomory) - 688 row cuts average 458.6 elements, 0 column cuts (0 active)  in 0.415 seconds - new frequency is -100
Cbc0014I Cut generator 2 (Knapsack) - 340 row cuts average 4.2 elements, 0 column cuts (0 active)  in 0.100 seconds - new frequency is 1
Cbc0014I Cut generator 3 (Clique) - 0 row cuts average 0.0 elements, 0 column cuts (0 active)  in 0.002 seconds - new frequency is -100
Cbc0014I Cut generator 4 (MixedIntegerRounding2) - 0 row cuts average 0.0 elements, 0 column cuts (0 active)  in 0.548 seconds - new frequency is -100
Cbc0014I Cut generator 5 (FlowCover) - 0 row cuts average 0.0 elements, 0 column cuts (0 active)  in 0.036 seconds - new frequency is -100
Cbc0010I After 0 nodes, 1 on tree, -5 best solution, best possible -11.953287 (4.48 seconds)
Cbc0038I Full problem 322 rows 511 columns, reduced to 120 rows 133 columns
Cbc0038I Full problem 322 rows 511 columns, reduced to 91 rows 110 columns
Cbc0038I Full problem 322 rows 511 columns, reduced to 85 rows 97 columns
Cbc0016I Integer solution of -6 found by strong branching after 35999 iterations and 328 nodes (8.91 seconds)
Cbc0038I Full problem 322 rows 511 columns, reduced to 125 rows 150 columns
Cbc0038I Full problem 322 rows 511 columns, reduced to 121 rows 138 columns
Cbc0038I Full problem 322 rows 511 columns, reduced to 129 rows 149 columns
Cbc0038I Full problem 322 rows 511 columns, reduced to 92 rows 113 columns
Cbc0010I After 1000 nodes, 6 on tree, -6 best solution, best possible -11.387254 (16.27 seconds)
Cbc0038I Full problem 322 rows 511 columns, reduced to 155 rows 187 columns
Cbc0038I Full problem 322 rows 511 columns, reduced to 128 rows 149 columns
Cbc0001I Search completed - best objective -6, took 132128 iterations and 1488 nodes (22.37 seconds)
Cbc0032I Strong branching done 6410 times (141017 iterations), fathomed 69 nodes and fixed 368 variables
Cbc0035I Maximum depth 20, 15691 variables fixed on reduced cost
Cuts at root node changed objective from -12.0585 to -11.9533
Probing was tried 40 times and created 0 cuts of which 0 were active after adding rounds of cuts (0.151 seconds)
Gomory was tried 40 times and created 688 cuts of which 0 were active after adding rounds of cuts (0.415 seconds)
Knapsack was tried 565 times and created 2052 cuts of which 22 were active after adding rounds of cuts (0.661 seconds)
Clique was tried 40 times and created 0 cuts of which 0 were active after adding rounds of cuts (0.002 seconds)
MixedIntegerRounding2 was tried 40 times and created 0 cuts of which 0 were active after adding rounds of cuts (0.548 seconds)
FlowCover was tried 40 times and created 0 cuts of which 0 were active after adding rounds of cuts (0.036 seconds)
TwoMirCuts was tried 1 times and created 0 cuts of which 0 were active after adding rounds of cuts (0.000 seconds)
Coin0505I Presolved problem not optimal, resolve after postsolve
Coin0505I Presolved problem not optimal, resolve after postsolve
Cgl0013I Postprocessed model is infeasible - possible tolerance issue - try without preprocessing
13 relaxed row infeasibilities - summing to 146.742
13 relaxed row infeasibilities - summing to 146.742
16 relaxed row infeasibilities - summing to 231.742

Result - Optimal solution found

Objective value:                6.00000000
Enumerated nodes:               1488
Total iterations:               132128
Time (CPU seconds):             22.45
Time (Wallclock seconds):       22.45

Option for printingOptions changed from normal to all
Total time (CPU seconds):       22.53   (Wallclock seconds):       22.53
`

**Comment by odow** [comment]
Closing because this issue is unrelated to GLPK, and `jump-dev` is for Julia packages, not Python.

If you have a question about Cbc in Julia, please post on the Community forum: https://discourse.julialang.org/c/domain/opt/13

If you are using Pyomo or PuLP, please post on their forums.
